In [1]:
#1. What is a Python library? Why ^o we use Python libraries?

In [ ]:
'''A Python library is a collection of functions and methods that allow you to perform many actions without
writing your own code for each action. Libraries typically contain reusable code modules that can be easily 
integrated into your own programs to extend their functionality.'''



In [2]:
#2. What is the ^ifference between Numpy array an^ List?

In [ ]:
'''
NumPy Array: NumPy arrays are more efficient and faster than Python lists,
especially for large datasets. They use less memory and provide better performance for numerical operations.
List: Python lists are slower and consume more memory due to the overhead of storing type information and other metadata.
 NumPy arrays are preferable for numerical and scientific computing due to their efficiency and advanced functionality, while Python lists are more versatile for 
 general-purpose programming.'''


In [ ]:
#3. Fin^ the shape, size an^ ^imension of the following array?
'''[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]'''

In [3]:
import numpy as np

In [6]:
array=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [7]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
#shape
array.shape

(3, 4)

In [10]:
#size
array.size

12

In [11]:
#dimension
array.ndim

2

In [ ]:
#4. Write python co^e to access the first row of the following array?

'''[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]'''

In [12]:
array1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [13]:
array1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
#accessing first row

first_row=array1[0]
print(first_row)

[1 2 3 4]


In [ ]:
'''
5. How ^o you access the element at the thir^ row an^ fourth column from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]'''

In [19]:
array2=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [20]:
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
#access the element at the thir^ row an^ fourth column

ele=array2[2,3]
print(ele)


12


In [ ]:
'''
    6. Write co^e to extract all o^^-in^exe^ elements from the given numpy array?

    [[1, 2, 3, 4]

    [5, 6, 7, 8],

    [9, 10, 11, 12]]'''

In [25]:
array4=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [26]:
array4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
od_index=array4[1::1,1::2]
print(od_index)

[[ 6  8]
 [10 12]]


In [ ]:
#7. How can you generate a ran^om 3x3 matrix with values between 0 an^ 1

In [39]:
random_matx=np.random.rand(3,3)

In [40]:
print(random_matx)

[[0.93958171 0.06098291 0.2754961 ]
 [0.16557257 0.81118569 0.32910261]
 [0.60733995 0.45075845 0.59837729]]


In [ ]:
#8. Describe the ^ifference between np.ran^om.ran^ an^ np.ran^om.ran^n?

In [ ]:
'''
np.random.rand and np.random.randn are both functions from the NumPy library used to generate arrays of random numbers

np.random.rand: Uniform distribution between 0 and 1.
np.random.randn: Standard normal distribution with mean 0 and standard deviation 1.

np.random.rand: When random values within a fixed range (0 to 1) are needed.
np.random.randn: When random values that follow a normal distribution are needed, often used in statistical modeling and simulations.'''


In [ ]:
'''


9. Write co^e to increase the ^imension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]'''

In [41]:
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

In [42]:
#increasing dimensions
expanded_array = np.expand_dims(array, axis=0)

In [44]:
print(expanded_array.shape)

(1, 3, 4)


In [ ]:
'''
0. How to transpose the following array in NumPy?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]'''


In [46]:
array=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [47]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [49]:
trans_array=np.transpose(array)
print("The transpose array:" , trans_array)

The transpose array: [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [ ]:
'''
11. Consi^er the following matrix:

Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]


Perform the following operation using Python1
,+ I(dex wiLe multiplicatio'
]+ Matix multiplicatio'
+ Add both the maticK
-+ Subtact matix B om 
+ Diide Matix B by A'''


In [51]:
A2=np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
B2=np.array([[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]])

In [53]:
#Index wise multiplication
indx_mul=A2*B2
print("Index wise multiplication:",indx_mul)

Index wise multiplication: [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


In [55]:
# Matix multiplicatio'

matx_mul=np.dot(A2,B2.T)
print("Matrix Multiplication:",matx_mul)

Matrix Multiplication: [[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]


In [56]:
#Add both the maticK
sum_matx=A2+B2
print("Addition:",sum_matx)

Addition: [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [57]:
#-+ Subtact matix B om 
sub_matx=A2-B2
print("Subtraction:",sub_matx)

Subtraction: [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [58]:
#+ Diide Matix B by A
div_matx=A2/B2
print("Divide:",div_matx)

Divide: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#12.  Which function in Numpy can be use^ to swap the byte or^er of an array?

In [ ]:
'''The numpy.ndarray.byteswap function to swap the byte order of an array. 
This function is useful when you need to handle data with different byte orders or endian formats.'''

In [ ]:
# What is the significance of the np.linalg.inv function?

In [ ]:
'''
The np.linalg.inv function in NumPy is used to compute the inverse of a square matrix.'''

In [ ]:
#14. What ^oes the np.reshape function ^o, an^ how is it use^

In [ ]:
'''
The np.reshape function in NumPy is used to change the shape or dimensions of an existing array without changing its data.
It allows you to create a new view of the array with a different shape while keeping the same data.'''

In [ ]:
#15. What is broa^casting in Numpy?

In [ ]:
'''
Broadcasting in NumPy is a powerful mechanism that allows NumPy to perform operations on arrays of different shapes in a way that 
simplifies the code and avoids the need for explicit loops. It makes it possible to perform arithmetic operations on arrays that do 
not have the same dimensions by automatically expanding the smaller array to match 
the shape of the larger array.'''